'use strict'

const { createE2ESandbox } = require('../../../service-sandbox')

describe('APITemplate.io Service (e2e)', () => {
  let sandbox
  let service
  let testValues

  beforeAll(() => {
    sandbox = createE2ESandbox('apitemplate')
    require('../src/index.js')

    try {
      sandbox.validateConfigs()
    } catch (error) {
      console.log(error)
      process.exit(1)
    }

    service = sandbox.getService()
    testValues = sandbox.getTestValues()
  })

  afterAll(() => {
    sandbox.cleanup()
  })

  // ── Account ──

  describe('getAccountInformation', () => {
    it('returns account info with expected shape', async () => {
      const result = await service.getAccountInformation()

      expect(result).toHaveProperty('status', 'success')
      expect(result).toHaveProperty('plan')
    })
  })

  // ── Templates ──

  describe('listTemplates', () => {
    it('returns templates array', async () => {
      const result = await service.listTemplates()

      expect(result).toHaveProperty('status', 'success')
      expect(Array.isArray(result.templates)).toBe(true)
    })
  })

  // ── Dictionary ──

  describe('getTemplatesDictionary', () => {
    it('returns dictionary items with label and value', async () => {
      const result = await service.getTemplatesDictionary({})

      expect(result).toHaveProperty('items')
      expect(Array.isArray(result.items)).toBe(true)
      expect(result).toHaveProperty('cursor', null)

      if (result.items.length > 0) {
        expect(result.items[0]).toHaveProperty('label')
        expect(result.items[0]).toHaveProperty('value')
      }
    })

    it('filters by search term', async () => {
      const allResult = await service.getTemplatesDictionary({})
      const searchResult = await service.getTemplatesDictionary({ search: 'zzz_nonexistent_zzz' })

      expect(searchResult.items.length).toBeLessThanOrEqual(allResult.items.length)
    })
  })

  // ── Objects ──

  describe('listObjects', () => {
    it('returns objects array with pagination', async () => {
      const result = await service.listObjects(5, 0)

      expect(result).toHaveProperty('status', 'success')
      expect(Array.isArray(result.objects)).toBe(true)
    })
  })

  // ── PDF Generation ──

  describe('createPdf', () => {
    let transactionRef

    it('creates a PDF from a template', async () => {
      const templateId = testValues.pdfTemplateId

      if (!templateId) {
        console.log('Skipping createPdf: no pdfTemplateId in testValues')
        return
      }

      const result = await service.createPdf(templateId, {})

      expect(result).toHaveProperty('status', 'success')
      expect(result).toHaveProperty('download_url')
      expect(result).toHaveProperty('transaction_ref')

      transactionRef = result.transaction_ref
    }, 60000)

    it('deletes the generated PDF object', async () => {
      if (!transactionRef) {
        console.log('Skipping deleteObject: no transactionRef from createPdf')
        return
      }

      const result = await service.deleteObject(transactionRef)

      expect(result).toHaveProperty('status', 'success')
    })
  })

  // ── PDF from HTML ──

  describe('createPdfFromHtml', () => {
    let transactionRef

    it('creates a PDF from raw HTML', async () => {
      const result = await service.createPdfFromHtml(
        '<html><body><h1>E2E Test</h1><p>Generated by test runner.</p></body></html>'
      )

      expect(result).toHaveProperty('status', 'success')
      expect(result).toHaveProperty('download_url')
      expect(result).toHaveProperty('transaction_ref')

      transactionRef = result.transaction_ref
    }, 60000)

    it('deletes the generated HTML-to-PDF object', async () => {
      if (!transactionRef) {
        console.log('Skipping deleteObject: no transactionRef from createPdfFromHtml')
        return
      }

      const result = await service.deleteObject(transactionRef)

      expect(result).toHaveProperty('status', 'success')
    })
  })

  // ── Image Generation ──

  describe('createImage', () => {
    let transactionRef

    it('creates an image from a template', async () => {
      const templateId = testValues.imageTemplateId

      if (!templateId) {
        console.log('Skipping createImage: no imageTemplateId in testValues')
        return
      }

      const result = await service.createImage(templateId, {})

      expect(result).toHaveProperty('status', 'success')
      expect(result).toHaveProperty('download_url')
      expect(result).toHaveProperty('transaction_ref')

      transactionRef = result.transaction_ref
    }, 60000)

    it('deletes the generated image object', async () => {
      if (!transactionRef) {
        console.log('Skipping deleteObject: no transactionRef from createImage')
        return
      }

      const result = await service.deleteObject(transactionRef)

      expect(result).toHaveProperty('status', 'success')
    })
  })
})
